name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  test:
    name: "Test package ${{ matrix.pkg }} on GAP-${{ matrix.gap-version }}"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name 
    
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - master
          - 4.14.0
          - 4.13.1
          - 4.13.0
        pkg:
          - example
          - gapdoc
          - primgrp
          - smallgrp

    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-full

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - shell: bash
        run: |
          apt update && apt install sudo libcurl4-openssl-dev -y
          SCRIPT_DIR=$PWD
          cd $GAP_HOME/pkg/${{ matrix.pkg }}
          gap $SCRIPT_DIR/makecitation.g -c "QuitGap();"
          cat $GAP_HOME/pkg/${{ matrix.pkg }}/CITATION.cff

      - name: "Validate citation"
        uses: dieghernan/cff-validator@v3
        with:
          install-r: true
          citation-path: /opt/gap/pkg/${{ matrix.pkg }}/CITATION.cff
