name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  test:
    name: "Test package ${{ matrix.pkg }}"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name 
    
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - example
          - gapdoc
          - primgrp
          - smallgrp

    container:
      image: ghcr.io/stertooy/gda-image:master-full

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - shell: bash
        run: |
          SCRIPT_DIR=$PWD
          cd $GAP_HOME/pkg/${{ matrix.pkg }}
          gap $SCRIPT_DIR/makecitation.g -c "QuitGap();"
          cat $GAP_HOME/pkg/${{ matrix.pkg }}/CITATION.cff
          cp $GAP_HOME/pkg/${{ matrix.pkg }}/CITATION.cff $SCRIPT_DIR/CITATION.cff

      - name: "Validate citation"
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
